DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS name CASCADE;

CREATE TABLE vendors {
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
}

CREATE TABLE items {
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  Item_quantity INTEGER NOT NULL,
  location VARCHAR(255) NOT NUll,
  Created_at TIMESTAMP NOT NULL,
  vendor_id INTEGER REFERENCES vendors(id) ON DELETE CASCADE
}