DROP TABLE IF EXISTS vendors CASCADE;
DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE vendors (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);

CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  Item_quantity INTEGER NOT NULL,
  location VARCHAR(255) NOT NUll,
  Created_at TIMESTAMP NOT NULL,
  Total MONEY NOT NULL,
  vendor_id INTEGER REFERENCES vendors(id) ON DELETE CASCADE,
  status INTEGER DEFAULT 0
);